= Background

This chapter introduces the concepts and technologies that underpin the TUMPeer backend. Each section describes what a concept is, explains its relevance to TUMPeer, and identifies the authoritative literature from which this thesis draws.

== Peer Assessment in Education

Peer assessment is a practice in which students evaluate each other's work using defined criteria and provide scores or feedback based on that evaluation. Topping @topping1998peer defines it as an arrangement in which individuals consider the amount, level, value, or quality of products or outcomes of their peers of similar status and provide feedback accordingly. The practice serves two complementary educational functions simultaneously: students who receive peer feedback gain additional perspectives on their work beyond what a single instructor can provide for an entire course cohort @nicol2010monologue @cho2010revision; students who give feedback develop evaluative judgment by applying criteria to artefacts other than their own. Strickroth @strickroth2019peer provides empirical support for both effects in a peer code review study: results indicate that giving feedback can change the reviewer's view on their own submission regarding its complete correctness, and the majority of students valued seeing other solutions.

For peer scores to contribute reliably to final grades, several structural factors are important. First, the evaluation criteria should be explicit and criterion-referenced. Falchikov and Goldfinch @falchikov2000student show in a meta-analysis of 48 higher education studies that peer assessment demonstrates substantial agreement with instructor grading, and that this agreement is influenced by factors such as the use of explicit assessment criteria. Studies employing explicit criteria tend to produce closer alignment between peer and instructor marks than those relying on less structured judgments. Second, the process should preserve mutual anonymity. When reviewers know the identity of the submission author — or when authors know who reviewed them — evaluations may reflect interpersonal relationships rather than the quality of the submitted work. Prior research indicates that anonymity in peer assessment can encourage more candid feedback and reduce the influence of interpersonal relationships @rod2022doubleblind. Prior work shows that when peer review is structured through explicit evaluation criteria, supported by clear guidance for reviewers, and aligned with course learning objectives, it can effectively complement instructor feedback and actively engage students in the learning process @brown2019peer @indriasari2020review. TUMPeer adopts this approach by enforcing rubric-based evaluation through structured review forms with scale-based questions.

Berrezueta-Guzman, Krusche, and Wagner @berrezueta2025coders apply both conditions in a large introductory programming course at TUM. Students used a detailed rubric to evaluate 2D game projects produced by peer teams. The study reports a Pearson correlation of $r = 0.55$ between peer scores and instructor scores, with a root mean square error (RMSE) of 14.87 for the first assigned reviewer, indicating moderate grading accuracy under structured conditions. A post-assessment survey finds that 83 percent of students enjoyed the evaluator role and that all 47 teams considered the peer evaluations fair. These results from TUM's own instructional context directly motivate the design choices in TUMPeer: rubric-based scoring as the sole quantitative evaluation mechanism and double-blind anonymity enforced at the API level.

== Representational State Transfer

Representational State Transfer (REST) is an architectural style for distributed hypermedia systems defined by Fielding @fielding2000architectural, in which a client communicates with a server through a uniform interface of standard HTTP methods and each request carries all the information needed to process it. TUMPeer exposes a REST API that the React frontend consumes; the stateless request model supports horizontal scaling because no server-side affinity is required for ordinary operations @fielding2000architectural.

== Layered Software Architecture

A layered architecture organises a system into horizontal tiers, each with a single defined responsibility that communicates only with the tier directly below it @buschmann1996posa. The pattern enforces separation of concerns, bounds the impact of any change to a single layer, and makes each layer independently testable. How TUMPeer applies this pattern is described in @sec-subsystem-decomposition.

== Spring Boot and Java Persistence

Spring Boot#footnote[Spring Boot Documentation: https://docs.spring.io/spring-boot/] is an opinionated configuration layer for the Spring Framework that auto-configures components and produces self-contained executable JARs; TUMPeer uses Spring Boot 3 on Java 21. Spring Security#footnote[Spring Security Documentation: https://docs.spring.io/spring-security/] manages authentication and authorisation at the HTTP filter level, maintaining session state through an HTTP-only cookie and enforcing per-course role checks at each endpoint. Spring Data JPA#footnote[Spring Data JPA Documentation: https://docs.spring.io/spring-data/jpa/], backed by Hibernate, provides a typed repository abstraction that maps Java entity classes to database tables and translates repository method declarations to SQL. Flyway#footnote[Flyway Documentation: https://flywaydb.org/documentation/] applies versioned SQL migration scripts on startup, ensuring that every environment runs against the same schema without manual database administration.

== PostgreSQL and Relational Data Modeling

PostgreSQL#footnote[PostgreSQL Documentation: https://www.postgresql.org/docs/] is an open-source relational database with full SQL and ACID transaction support, which guarantees that concurrent operations do not corrupt shared state. TUMPeer uses PostgreSQL 17; the hierarchical structure of academic data maps naturally to a relational schema enforced by foreign-key constraints, as described in @sec-data-model.
