= Related Work

This chapter surveys platforms and research relevant to TUMPeer, examining tools used for peer review in educational settings, discussing research on automated assessment and fair reviewer allocation, and identifying the specific gap that TUMPeer fills.

== Existing Peer Review Platforms

Two categories of system are the most relevant comparisons to TUMPeer: Artemis, a TUM-developed exercise and assessment platform, and a class of general-purpose learning management systems with peer assessment modules. Both are used in university settings to support assignment assessment, and both informed design decisions in TUMPeer. The comparison below examines each along three dimensions: anonymity enforcement, degree of automation, and fit to TUM's institutional context.

*Artemis* is an exercise and assessment management system developed at TUM @krusche2018artemis. It supports programming exercises with automated test-based grading: students push code to a repository, the platform executes a preconfigured test suite, and the result is presented as an immediate score. TUM courses rely on Artemis for programming assignments, and its deep integration with TUM infrastructure makes it the natural starting point for comparison.

However, Artemis does not implement double-blind peer review — its primary grading mechanism is a test suite, not student evaluators — and it does not include a background scheduler that transitions submission statuses or allocates reviewers at deadlines. TUMPeer targets a different scenario: project-level file submissions where quality cannot be determined by a test suite and where rubric-based human evaluation is the more appropriate grading mechanism. The two systems are complementary: Artemis handles deterministic, automated grading of programming tasks, and TUMPeer handles peer evaluation of project submissions.

General-purpose learning management systems used by universities commonly include peer assessment modules that support criterion-based rubrics and some form of reviewer allocation. In these systems, anonymity is typically a display-level configuration option rather than an architectural guarantee: the platform hides names in the review interface, but identity separation is not enforced at the API level and depends on correct frontend configuration. Phase transitions between submission and review likewise tend to require explicit instructor intervention rather than happening automatically when a deadline passes. Being general-purpose tools, they carry no institution-specific constraints and would require substantial configuration to match the workflow and grading rules of a specific course programme.

== Automated Assessment and Review Allocation

Research on automated and semi-automated peer assessment informs several TUMPeer design decisions.

Kulkarni et al. @kulkarni2013peer study peer and self-assessment across two iterations of a large online course and find that peer grades correlate well with instructor grades. Their analysis shows that aggregating scores across multiple peer reviewers improves agreement with instructor evaluations, with increasing numbers of reviewers further improving accuracy, although with diminishing returns. This finding motivates the TUMPeer requirement that each submission receives a configurable number of peer reviews, as relying on a single reviewer can introduce substantial variance in the final grade.

Raman and Joachims @raman2014ordinal develop probabilistic models for estimating true submission quality from peer grades in an ordinal setting, demonstrating that model-based correction improves grading accuracy over naive aggregation. TUMPeer operates on cardinal scores rather than ordinal rankings, but the motivation is analogous: the outlier detection rule replaces the peer average with the instructor score when any peer score deviates by more than 20 percentage points, providing a transparent correction mechanism that does not require a probabilistic model. Berrezueta-Guzman, Krusche, and Wagner @berrezueta2025coders provide empirical evidence of deviations between peer and instructor scores in a TUM programming course: peer evaluations show moderate agreement with instructor scores while individual deviations still occur, which motivates the use of a fixed threshold (20 percentage points) in this system.

== Research Gap

The platforms and studies surveyed above address subsets of the peer review problem in different instructional contexts. No surveyed system combines the following capabilities in a single system: registration restricted to TUM-specific email domains, automatic load-balanced reviewer allocation that distributes an equal number of review tasks per student, multi-criteria rubric scoring as the sole quantitative evaluation mechanism, a background scheduler that transitions submission and review statuses at deadlines without instructor intervention, an outlier detection rule that substitutes the instructor score when peer evaluations deviate substantially, mutual double-blind anonymity enforced at the API response level throughout the entire workflow, and anonymised per-criterion score statistics released to both instructors and students after grade publication.

TUMPeer addresses this gap by implementing the complete peer review lifecycle — from TUM-restricted registration through rubric configuration, file submission, automatic allocation, review collection, outlier-corrected grade computation, and result release — within a single backend system designed specifically for the constraints and workflow of TUM courses.