= Summary

This thesis designed and implemented the TUMPeer backend: a four-layer Spring Boot REST API backed by a PostgreSQL database that automates the peer review lifecycle for university courses at TUM. The implementation covers every phase of the lifecycle from user registration through grade release and translates the ten functional requirements and five quality attributes stated in Chapter 4 into working code.

== Realized Goals

The backend addresses all ten functional requirements. FR1 and FR2 are covered by a two-step email verification flow, BCrypt-hashed password storage, session-based login with configurable lifetime, and a five-session concurrency limit. FR3 and FR4 are covered by course and member management with CSV import, assignment creation with rubric questions, and deadline PATCH endpoints that trigger the appropriate status reversals when a closed window reopens. FR5 is covered by hard deadline enforcement at the endpoint level and UUID-prefixed file storage. FR6 is covered by the balanced allocation algorithm with a rotating position tiebreaker that prevents systematic reviewer clustering. FR7 and FR8 are covered by draft and submit review endpoints that enforce the review window and protect reviewer anonymity, and by a per-submission instructor grading endpoint. FR9 is covered by the `release-grades` endpoint, which applies the ±20pp outlier rule and records the grading branch in an auditable field. FR10 is covered by `SubmissionStatusScheduler`, which runs every 60 seconds and applies all deadline-driven transitions idempotently.

All five quality attributes are supported by the implementation. BCrypt hashing, HTTP-only session cookies, and Bucket4j rate limiting applied to all API endpoints address QA1 (Security). The idempotent scheduler addresses QA2 (Reliability). The grade calculation logic and endpoint-level deadline enforcement address QA3 (Correctness). The stateless REST design supports QA4 (Scalability) because each request carries all the context needed to process it independently; quantitative load testing under large-cohort conditions remains outside the scope of this thesis. The layered architecture addresses QA5 (Maintainability): the separation of controller, service, and repository layers keeps each layer's responsibility narrow and enables independent verification of business logic; a unit test suite covering the service layer was contributed by a team member outside the scope of this thesis.

The implementation was verified through manual end-to-end testing in which student and instructor accounts were created, assignments with rubrics and deadlines were configured, the full submission and review lifecycle was executed, and scheduler-driven status transitions were confirmed against live deadline boundaries. The grading logic, including the outlier detection rule and the four calculation branches, was exercised by constructing review scenarios with varying peer and instructor score combinations.

== Limitations

The backend was designed with scalability in mind: requests are stateless, the service layer processes each operation independently, and no global locks are held during normal workflow operations. These properties suggest the system can handle concurrent access from large courses without correctness failures. However, this has not been validated under load. No performance tests were conducted with simulated student cohorts, and no measurements of response time or throughput under concurrent requests exist. The scalability claim therefore rests on architectural design decisions rather than empirical evidence, and load testing under realistic operating conditions remains an open item for future work.

== Conclusion

This thesis designed and implemented the TUMPeer backend — a REST API and PostgreSQL database that automates the peer review lifecycle for university courses at TUM. The platform addresses the gap identified in the introduction: the absence of a dedicated backend that enforces TUM-specific constraints, allocates reviewers equitably, and drives all deadline-based state changes without instructor intervention. Every phase of the peer review lifecycle, from user registration and course setup through submission, review, and grade release, is covered by a working implementation verified through manual end-to-end testing.

Four technical contributions form the core of the work. The layered Spring Boot architecture separates security, request handling, business logic, and data access into four distinct, independently testable layers, keeping each layer's responsibility narrow and its behaviour verifiable in isolation. The review allocation algorithm distributes peer review tasks evenly across a cohort while ensuring no student reviews their own work; a rotating position tiebreaker prevents the reviewer clustering that a simpler deterministic tiebreaker would produce. The scheduler-driven status machine enforces deadline transitions within 60 seconds of a deadline passing under normal server load, without requiring any client to trigger the change, and processes every assignment idempotently on each execution. The outlier-detection grading system computes final scores according to the ±20pp rule, includes the instructor's own peer review contribution in the grade average when they participated as a reviewer, and records the grading branch in an auditable field that instructors can inspect after release.

The backend addresses all five quality attributes stated in Chapter 4: passwords are BCrypt-hashed, sessions are confined to HTTP-only cookies, rate limiting is applied to all API endpoints, all status transitions are idempotent, and the layered design enables independent verification of every business rule. The implementation covers the scope of the objectives stated in the introduction.

== Future Work

Three directions offer clear paths to extending TUMPeer's backend. OAuth2 integration with TUM's identity provider would replace the current email-based registration with single sign-on. TUM's OAuth2 infrastructure became accessible only at the end of the development period, which made integration infeasible within the thesis timeline. Replacing the custom verification flow with OAuth2 would eliminate manual account creation, enforce TUM identity at the authentication layer, and remove the dependency on a third-party SMTP relay for verification emails.

The ±20pp outlier detection rule provides a simple, auditable grading decision, but it does not account for the distribution of peer scores or for systematic reviewer bias. A natural extension would apply statistical outlier detection — for example, flagging scores that deviate by more than one standard deviation from the peer mean — and weight reviewer scores by their historical alignment with instructor grades. TUMPeer's data model already supports this direction: the `ReviewScore` and `SubmissionGrade` tables retain the full per-question scoring history needed to build reviewer reliability profiles over successive assignments. A related extension would allow the instructor to manually override the applied calculation rule per submission — for example, choosing between peer average, instructor score, or a combined average via a dropdown when scores are inconsistent — rather than always relying on the automatic ±20pp decision.

Performance evaluation under realistic operating conditions is a third open direction. A natural next step would be to deploy the platform in real courses, starting with smaller cohorts, and measure response times and throughput to confirm that the allocation algorithm and scheduler perform within acceptable bounds. A comparison of the rotating-tiebreaker allocation against a random baseline would make the fairness improvement measurable rather than argued from the algorithm's structure alone.
